server:
  port: 7777
spring:
  application:
    name: API-GATEWAY
  boot:
    admin:
      client:
        url: http://localhost:8888
  cloud:
    gateway:
      discovery:
        locator:
          enable: true
          lower-case-service-id: true
  main:
    web-application-type: reactive
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true


management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    show-details: always