server:
  port: 8761
spring:
  application:
    name: EUREKA-SERVER
  boot:
    admin:
      client:
        url: http://host.docker.internal:8888
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
  instance:
    prefer-ip-address: true


management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    show-details: always